version: '3'

services:
  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          # - MONGO_INITDB_ROOT_USERNAME=root
          # - MONGO_INITDB_ROOT_PASSWORD=password
          - MONGO_INITDB_DATABASE=programr
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_PORT_27017_TCP_ADDR="10.0.75.1"
        ports:
            - 27017:27017
        volumes:
            # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - /home/jarid/database:/data/db


  programr:
        build: .
        container_name: "programr"
        volumes:
          - .:/usr/src/app
        ports:
          - 5000:5000
        links:
          - mongodb
        depends_on:
          - mongodb
        # command: "python ./src/programr/clients/events/majordomo/client.py --config ./bots/ryan/config.yaml --cformat yaml --logging ./bots/ryan/logging.yaml"
        command: "python ./src/programr/clients/restful/flask/client.py --config ./bots/Ryan/config.yaml --cformat yaml --logging ./bots/Ryan/logging.yaml"

xmlrpc:
    command: "python ./src/programr/rpcservices/xmlrpc_server.py"